spring.application.name=java
server.port=8080
# KEY
gemini.api.key=${OPENAI_API_KEY}
logging.level.root=INFO
# DB CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/ai_chat
spring.datasource.username=root
spring.datasource.password=${PASSWORD}
# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# OPTIONAL (fix dialect issue explicitly)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect